version: '2'

services:
    btelegr:
        build: btelegr
        container_name: btelegr
        hostname: btelegr
        restart: always
        environment:
            - TELEGRAM_TOKEN=411787988:AAFJ7JdB6gXfeoNNksru_cN-Eh9Ei8_1_PY
            - MONGO_URI=mongodb://user:user@ds149865.mlab.com:49865/ingressdb

# TODO I exposed all secrets as env variables, please, remove them and regenerate all tokens. Don't keep them in public repository!!!!!